version: '3.8'
services:
  server:
    build: ./server
    image: express/server:v1
    container_name: server-container
    ports:
      - '4000:4000'
    env_file:
      - ./server/.env
  
  client:
    build: ./client
    image: react/client:v1
    container_name: client-container
    ports:
      - '3000:3000'
    volumes:
      - ./client:/client
    tty: true
    stdin_open: true
